### ISSUE TITLE
Новые новости. Замечания.

### ISSUE THREAD

**Issue by stepanoff** [66ru/misc-verstka#87]
* [x] http://66demo.ru/news/incident/260/ - надо сделать нормальный wrapper для блока с каментами.

* [x] http://66demo.ru/news/incident/260/ - тут конец текста упирается в самый низ (т.е. до блока с другими новостями), а тут - http://66demo.ru/news/society/1066/ появляется куча белого пространства. Почему?

* [x] http://66demo.ru/news/society/1066/ непонятный верхний отступ у новости. Он зачем-то нужен?

* [x] подпись "Фото: Дмитрий Горчаков, архив 66.ru" не прижата к низу картинки

* [x] непропорционально ресайзятся фотки http://66demo.ru/news/ , а на 1024 вообще страх с пропорциями. Может, все-таки в бекграунд?

**Comment by anbelyaev** [comment]
@DarkAiR, про подпись «Фото: Дмитрий Горчаков, архив 66.ru»:

Блок `.news_single_content__photo-sign` должен быть сразу внутри блока `.splash-heading`, вот так:
![screen shot 2015-01-30 at 14 38 27](https://cloud.githubusercontent.com/assets/2402615/5973768/060d0bc4-a88e-11e4-9c52-200d38e19b74.png)

а не внутри `.splash-heading__shade`, как сейчас:
![screen shot 2015-01-30 at 14 37 52](https://cloud.githubusercontent.com/assets/2402615/5973786/40795de4-a88e-11e4-9122-6e329d4ff849.png)
