### ISSUE TITLE
Курсы валют. Мобильная версия.

### ISSUE THREAD

**Issue by stepanoff** [66ru/misc-verstka#88]
Для мобильной версии нужна версия этой страницы http://66.ru/bank/currency/

Мое видение примерно такое:

https://dl.dropboxusercontent.com/u/7486609/materials/currrency_mobile.jpg

**Comment by anbelyaev** [comment]
misc-verstka/mobile/rates.html

**Comment by stepanoff** [comment]
Круто.
Давай еще добавим возможность сортировки по столбцам.

**Comment by anbelyaev** [comment]
Да, точно.
