### ISSUE TITLE
Замечания по новым новостям 2

### ISSUE THREAD

**Issue by stepanoff** [66ru/misc-verstka#89]
* [x] В новости первая картинка вылазит за контент на 1024 https://dl.dropboxusercontent.com/u/7486609/bugs/new_news_1.png

* [x] На странице с новостью в блоке "Новости из рубрики" картинки ресайзятся средствами браузера с искажением пропорций https://dl.dropboxusercontent.com/u/7486609/bugs/new_news_1.png

* [x] http://66demo.ru/news/society/1066/ при залипании меню уходит за контент новости

* [x] http://66demo.ru/news/society/1066/ поиск по новостям. Не надо ли его выровнять по профилю пользователя? placeholder надо убирать при фокусе

* [x] http://66demo.ru/news/ тут опять у картинок качество из-за `width: 100%` страдает. Стили не те взяли?

**Comment by stepanoff** [comment]
* [ ] иконка у фоторепа http://66demo.ru/news/society/1066/ и новости с картинкой на 3 колонки в списке

* [ ] добавить нижнюю отбивку у каментов

**Comment by anbelyaev** [comment]
На странице с лентой блок `.grid` надо засунуть сразу в `#body.ie_layout`, вот так:
![screen shot 2015-03-23 at 21 42 20](https://cloud.githubusercontent.com/assets/2402615/6785251/4bb9507e-d1a6-11e4-96a9-fc6705a82e65.png)

Сейчас он обернут в `.layout > .layout__base` и это плохо:
![screen shot 2015-03-23 at 21 42 53](https://cloud.githubusercontent.com/assets/2402615/6785280/776f18ca-d1a6-11e4-8733-4a2858882d82.png)

**Comment by anbelyaev** [comment]
На странице новости заглавная маленькая картинка сейчас обернута в `.news_single_content__photo`, это плохо:
![screen shot 2015-03-24 at 17 12 30](https://cloud.githubusercontent.com/assets/2402615/6801419/4a6487b8-d249-11e4-928a-0b5930eca174.png)

Надо убрать обертку и назначить картинке её класс — `img.news_single_content__photo` — вот так:
![screen shot 2015-03-24 at 17 13 10](https://cloud.githubusercontent.com/assets/2402615/6801453/94deff26-d249-11e4-8095-9e2a81ba254d.png)

**Comment by anbelyaev** [comment]
На странице с новостью сейчас мы спрятали (и открываем по кнопке «Обсудить») элемент `.comms__comments`, это плохо:
![screen shot 2015-03-24 at 17 18 51](https://cloud.githubusercontent.com/assets/2402615/6801539/6c7c63c4-d24a-11e4-88d3-f7c2f1dc1788.png)

Надо прятать/показывать весь блок `.comms`, вот так:
![screen shot 2015-03-24 at 17 23 15](https://cloud.githubusercontent.com/assets/2402615/6801547/8ddaa21a-d24a-11e4-83a1-2c528ab1689a.png)

**Comment by anbelyaev** [comment]
На странице с новостью у `.comms` уберите `style="margin-bottom: 0;"`.
